server:
  port: 8888

spring:
  application:
    name: multibackend-config-server
  profiles:
    include: git, vault
  cloud:
    config:
      server:
        native:
          searchLocations: /path
          order: 1
        git:
          uri: https://github.com/
        vault:
          host: 127.0.0.1
          port: 8200
          kvVersion: 2
          order: 2
